"""esquema inicial: sensors y readings

Revision ID: 21acf011a966
Revises: 
Create Date: 2026-08-07 21:30:40.955212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21acf011a966'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.create_foreign_key('fk_readings_sensor_id', 'sensors', ['sensor_id'], ['sensor_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_readings_sensor_id', type_='foreignkey')

    # ### end Alembic commands ###
