"""esquema completo: sensors, readings, alerts

Revision ID: 4e33ea8ef589
Revises:
Create Date: 2026-08-22 11:53:09.151623

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4e33ea8ef589"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sensors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sensor_id", sa.String(), nullable=False),
        sa.Column("sensor_type", sa.String(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("location", sa.String(), nullable=True),
        sa.Column("min_threshold", sa.Float(), nullable=True),
        sa.Column("max_threshold", sa.Float(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("sensors", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_sensors_sensor_id"), ["sensor_id"], unique=True
        )

    op.create_table(
        "readings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sensor_id", sa.String(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("unit", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["sensor_id"], ["sensors.sensor_id"], name="fk_readings_sensor_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("readings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_readings_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_readings_sensor_id"), ["sensor_id"], unique=False
        )

    op.create_table(
        "alerts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sensor_id", sa.String(), nullable=False),
        sa.Column("reading_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.Float(), nullable=False),
        sa.Column("threshold_breached", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["reading_id"], ["readings.id"], name="fk_alerts_reading_id"
        ),
        sa.ForeignKeyConstraint(
            ["sensor_id"], ["sensors.sensor_id"], name="fk_alerts_sensor_id"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_alerts_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_reading_id"), ["reading_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_alerts_sensor_id"), ["sensor_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("alerts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_alerts_sensor_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_reading_id"))
        batch_op.drop_index(batch_op.f("ix_alerts_created_at"))

    op.drop_table("alerts")
    with op.batch_alter_table("readings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_readings_sensor_id"))
        batch_op.drop_index(batch_op.f("ix_readings_created_at"))

    op.drop_table("readings")
    with op.batch_alter_table("sensors", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_sensors_sensor_id"))

    op.drop_table("sensors")
    # ### end Alembic commands ###
