"""esquema inicial: sensors y readings

Revision ID: 605f5409018b
Revises: 
Create Date: 2026-08-08 04:44:25.396578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '605f5409018b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=False),
    sa.Column('sensor_type', sa.String(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_sensor_id'), ['sensor_id'], unique=True)

    op.create_table('readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_id', sa.String(), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.sensor_id'], name='fk_readings_sensor_id'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_readings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_readings_sensor_id'), ['sensor_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_readings_sensor_id'))
        batch_op.drop_index(batch_op.f('ix_readings_created_at'))

    op.drop_table('readings')
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sensors_sensor_id'))

    op.drop_table('sensors')
    # ### end Alembic commands ###
