"""agregar indice a alert.reading_id

Revision ID: d8afeb2fe3fe
Revises: e9b12090ca8e
Create Date: 2026-08-17 17:38:50.056430

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "d8afeb2fe3fe"
down_revision: str | Sequence[str] | None = "e9b12090ca8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
