"""agregar tabla alerts y thresholds en sensors

Revision ID: e9b12090ca8e
Revises: 605f5409018b
Create Date: 2026-08-15 14:14:06.199929

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e9b12090ca8e"
down_revision: str | Sequence[str] | None = "605f5409018b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensors", schema=None) as batch_op:
        batch_op.add_column(sa.Column("min_threshold", sa.Float(), nullable=True))
        batch_op.add_column(sa.Column("max_threshold", sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sensors", schema=None) as batch_op:
        batch_op.drop_column("max_threshold")
        batch_op.drop_column("min_threshold")

    # ### end Alembic commands ###
